#!/bin/python
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.Dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 400)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.the_title = QtWidgets.QLabel(Dialog)
        self.the_title.setObjectName("the_title")
        self.gridLayout.addWidget(self.the_title, 0, 0, 1, 2)
        self.button_ok = QtWidgets.QPushButton(Dialog)
        self.button_ok.setObjectName("button_ok")
        self.gridLayout.addWidget(self.button_ok, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_3.addWidget(self.label_1, 0, QtCore.Qt.AlignRight)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignRight)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.input_1 = QtWidgets.QLineEdit(Dialog)
        self.input_1.setInputMask("")
        self.input_1.setPlaceholderText("")
        self.input_1.setClearButtonEnabled(False)
        self.input_1.setObjectName("input_1")
        self.verticalLayout_4.addWidget(self.input_1)
        self.input_2 = QtWidgets.QLineEdit(Dialog)
        self.input_2.setInputMask("")
        self.input_2.setPlaceholderText("")
        self.input_2.setClearButtonEnabled(False)
        self.input_2.setObjectName("input_2")
        self.verticalLayout_4.addWidget(self.input_2)
        self.input_3 = QtWidgets.QLineEdit(Dialog)
        self.input_3.setInputMask("")
        self.input_3.setPlaceholderText("")
        self.input_3.setClearButtonEnabled(False)
        self.input_3.setObjectName("input_3")
        self.verticalLayout_4.addWidget(self.input_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.button_cancel = QtWidgets.QPushButton(Dialog)
        self.button_cancel.setObjectName("button_cancel")
        self.gridLayout.addWidget(self.button_cancel, 3, 0, 1, 1)
        self.the_error = QtWidgets.QLabel(Dialog)
        self.the_error.setObjectName("the_error")
        self.gridLayout.addWidget(self.the_error, 1, 0, 1, 2)

        # buttons
        self.button_cancel.clicked.connect(self.exit_button_clicked)
        self.button_ok.clicked.connect(self.ok_button_clicked)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def exit_button_clicked(self):
        print("Exit button clicked")
        self.Dialog.close()

    def ok_button_clicked(self):
        x = []
        x.append(self.input_1.text())
        x.append(self.input_2.text())
        x.append(self.input_3.text())
        print("OK button clicked")
        for i in range(len(x)):
            print(x[i], end = ' ')
            if x[i] == '':
                err = f"Fields cannot be empty!"
                text = f"<p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">{err}</span></p>"
                print(err)
                self.the_title.setText(text)
                return
            else:
                print()
                print(tuple(x))
                self.Dialog.close()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.the_title.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">This is just a good looking test!</span></p></body></html>"))
        self.button_ok.setText(_translate("Dialog", "OK"))
        self.label_1.setText(_translate("Dialog", "First Item"))
        self.label_2.setText(_translate("Dialog", "Second Item"))
        self.label_3.setText(_translate("Dialog", "Third Item"))
        self.button_cancel.setText(_translate("Dialog", "Cancel"))
        self.the_error.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
