all:
	sh make.sh
# 	make ui
# 	make python
# 	# ./main.py
#
# python:
# 	python ./new.py
# 	python ./popup_alert.py
# 	python ./popup_input.py
#
# ui:
# 	# sh make.sh
# 	/usr/bin/pyrcc5 -o figure_rc.py figure.qrc
#
# force:
# 	make ui
# 	make python
# 	sh make.sh
